### ISSUE TITLE
"Sequence numbers are deprecated"

### ISSUE THREAD

**Issue by ryqiem** [Garee/pytodoist#17]
My code:
```python
from datetime import datetime
from pytodoist import todoist
from pytodoist.api import TodoistAPI
from credentials import *

#Setup todoists
user = todoist.login(user, password)

#Setup datetime objects
today_object = datetime.today().date()

#API setup
api = TodoistAPI()
response = api.login('##EMAIL##', '##PASSWORD##')
user_info = response.json()
user_api_token = user_info['token']

def copy_due(inp, outp):
    """
    Takes arguments
    inp: Input project
    outp: Output project

    and copies due tasks from inp to outp
    """
    #Setup projects
    output_id = user.get_project(outp).id
    due_tasks = user.get_project(inp).get_uncompleted_tasks()

    for task in due_tasks:
        if task.due_date is not None:
            date_object = datetime.strptime(task.due_date, '%a %d %b %Y %H:%M:%S %z').date()

            if today_object == date_object:
                notes = task.get_notes()

                label_ids = task.labels

                response = api.add_item(user_api_token, task.content, project_id=output_id, priority=task.priority, labels=str(label_ids))


                task.complete()

copy_due("Recurrent-tickler", "Solitary-actionable")
#copy_due("Tickler", "Solitary-actionable")
```

The error:
```
Traceback (most recent call last):
  File "/Volumes/home/Work/Tickler-Todoist/test.py", line 44, in <module>
    copy_due("Recurrent-tickler", "Solitary-actionable")
  File "/Volumes/home/Work/Tickler-Todoist/test.py", line 42, in copy_due
    task.complete()
  File "/usr/local/lib/python3.5/site-packages/pytodoist/todoist.py", line 1293, in complete
    _perform_command(self.project.owner, 'item_close', args)
  File "/usr/local/lib/python3.5/site-packages/pytodoist/todoist.py", line 200, in _perform_command
    _fail_if_contains_errors(response, command_uuid)
  File "/usr/local/lib/python3.5/site-packages/pytodoist/todoist.py", line 175, in _fail_if_contains_errors
    raise RequestError(response)
pytodoist.todoist.RequestError: {"error_tag":"ACCESS_DENIED","error_code":101,"http_code":403,"error_extra":{},"error":"Sequence numbers are deprecated. Please upgrade your client to switch to sync tokens or contact support at https:\/\/support.todoist.com. Deprecated functionality will be  completely disabled on 13 Feb 2016 at 9:00:00 GMT"}
```

The code has been working just fine for the last ~6 months – hope you have time to look at it! 👍

**Comment by Garee** [comment]
I haven't been able to reproduce the error and all of my tests still pass successfully. Can you please confirm that the error is still occurring for you?

The error message suggests that there was an authentication problem, can you please double check your credentials?

**Comment by ryqiem** [comment]
It's back! D:

```Traceback (most recent call last):
  File "test.py", line 48, in <module>
    copy_due("Recurrent-tickler", "Solitary-actionable")
  File "test.py", line 42, in copy_due
    task.complete()
  File "/home/martin/.local/lib/python3.5/site-packages/pytodoist/todoist.py", line 1293, in complete
    _perform_command(self.project.owner, 'item_close', args)
  File "/home/martin/.local/lib/python3.5/site-packages/pytodoist/todoist.py", line 200, in _perform_command
    _fail_if_contains_errors(response, command_uuid)
  File "/home/martin/.local/lib/python3.5/site-packages/pytodoist/todoist.py", line 175, in _fail_if_contains_errors
    raise RequestError(response)
pytodoist.todoist.RequestError: {"error_tag":"ACCESS_DENIED","error_code":101,"http_code":403,"error_extra":{},"error":"Sequence numbers are deprecated. Please upgrade your client to switch to sync tokens or contact support at https:\/\/support.todoist.com. Deprecated functionality was  disabled on 14 Feb 2016 at 17:00:00 GMT"}```

Maybe this line is significant? `Deprecated functionality was  disabled on 14 Feb 2016 at 17:00:00 GMT`

Do your unit tests still pass? My system hasn't been modified since I wrote that it was fixed.

**Comment by Garee** [comment]
The functionality is deprecated, but it has been so for nearly a year now with no issue.

My tests still pass therefore I think this may be an intermittent problem that I haven't yet encountered.

The issue may go away if the Todoist API is updated. If not, I could have a go at removing the deprecated functionality.

**Comment by ryqiem** [comment]
@Garee In my previous post the code includes:

`Deprecated functionality will be  completely disabled on 13 Feb 2016 at 9:00:00 GMT`

Whereas now it says:

`Deprecated functionality was disabled on 14 Feb 2016 at 17:00:00 GMT`

Perhaps Todoist messed up the year?

If you try to run my code with multiple tasks in the input project, you don't get the error?

**Comment by Garee** [comment]
I ran your example with hard coded credentials and it's working fine for me. I also re-ran the test suite and they all pass.

Are you still experiencing the issue @ryqiem ?

**Comment by amccaugh** [comment]
I'm getting something similar I believe, with the login_with_api_token() command.  When I run the line

`user = todoist.login_with_api_token(my_api_token)`

the response I get is


```
  File "C:\Anaconda2\lib\site-packages\pytodoist\todoist.py", line 92, in login_with_api_token
    return User(user_json)

  File "C:\Anaconda2\lib\site-packages\pytodoist\todoist.py", line 325, in __init__
    self.sync()

  File "C:\Anaconda2\lib\site-packages\pytodoist\todoist.py", line 361, in sync
    self.api_seq_no = response_json['seq_no']

KeyError: 'seq_no'
```

**Comment by Garee** [comment]
@ryqiem @amccaugh I have released a new version that uses version 7 of the Todoist sync API.

Please upgrade the package and let me know if it works or if you have any issues.

```
$ pip install pytodoist --upgrade
```

Thanks for reporting the issue.

**Comment by amccaugh** [comment]
Tested and it looks great, thanks!

**Comment by ryqiem** [comment]
After fixing a slight change in the task attributes from `due_date` `due_date_UTC`, it's working awesome here as well!

You're the man, @Garee!
