### ISSUE TITLE
Update to support version 8 of Todoist API

### ISSUE THREAD

**Issue by pete-adriano-debiase** [Garee/pytodoist#33]
Todoist seems to have updated their API to version 8, which has new endpoints. The following code:

    from pytodoist import todoist
    user = todoist.login('gary@garyblackwood.co.uk', 'pa$$w0rd')

now causes the following error to occur:

    Traceback (most recent call last):
      File "C:\Users\gary_blackwood\todoist_apitest.py", line 3, in <module>
        user = todoist.login('gary@garyblackwood.co.uk', 'pa$$w0rd')
      File "C:\Python3\lib\site-packages\pytodoist\todoist.py", line 45, in login
        user = _login(API.login, email, password)
      File "C:\Python3\lib\site-packages\pytodoist\todoist.py", line 102, in _login
        return User(user_json)
      File "C:\Python3\lib\site-packages\pytodoist\todoist.py", line 310, in __init__
        self.sync()
      File "C:\Python3\lib\site-packages\pytodoist\todoist.py", line 344, in sync
        _fail_if_contains_errors(response)
      File "C:\Python3\lib\site-packages\pytodoist\todoist.py", line 175, in _fail_if_contains_errors
        raise RequestError(response)
    pytodoist.todoist.RequestError: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
    <title>410 Gone</title>
    <h1>Gone</h1>
    <p>This API endpoint is no longer available. Please refer to our documentation to upgrade your client to use the latest API version: https://developer.todoist.com</p>

Is there any possibility of updating `pytodoist` to support Todoist API version 8?

**Comment by Garee** [comment]
Thanks for creating this issue. I'll look into what is required to update and should hopefully get the library up and running again soon.

**Comment by Garee** [comment]
I've released a new version (v2.1.4) that uses version 8 of the API. Let me know if you encounter any issues - thanks.

**Comment by pete-adriano-debiase** [comment]
Everything seems to be working normally as far as I can tell. Thank you so much for pushing a patch so quickly!
